-- Add quality demo reviews for each vendor

-- NauticTech Solutions (Free Tier) - id: 1
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 1, 'review-nautic-1', 'Captain James Morrison', 'Yacht Captain', 'Sea Dream', 'Navigation System Installation', 4.5, 5, 4, 5, 5, 4, 'NauticTech delivered an excellent navigation system for our 85-foot yacht. The installation was professional and the system works flawlessly. Great value for the price point.', '2024-10-15', 1, 0),
(2, 1, 'review-nautic-2', 'Michael Chen', 'Yacht Owner', 'Pacific Explorer', 'Electronics Upgrade', 4, 4, 4, 4, 4, 4, 'Solid service and reliable products. The team was knowledgeable and responsive throughout the project. Would recommend for basic to mid-level electronics needs.', '2024-09-22', 1, 0);

-- MarineAudio Pro (Free Tier) - id: 4
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 4, 'review-audio-1', 'Sarah Williams', 'Interior Designer', 'Serenity', 'Audio System Installation', 4.5, 5, 4, 4, 5, 5, 'MarineAudio Pro provided an exceptional audio system that exceeded our expectations. The sound quality is outstanding and the installation was clean and professional.', '2024-11-01', 1, 1),
(2, 4, 'review-audio-2', 'David Martinez', 'Yacht Manager', 'Blue Horizon', 'Entertainment System', 4, 4, 4, 4, 4, 4, 'Good quality audio equipment at a competitive price. The system has been reliable and sounds great throughout the yacht.', '2024-08-18', 1, 0);

-- NavTech Marine Systems (Tier 1) - id: 7
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 7, 'review-navtech-1', 'Captain Robert Anderson', 'Professional Captain', 'Oceanus', 'Complete Navigation Suite', 5, 5, 5, 5, 5, 4, 'NavTech installed the most advanced navigation system I have worked with. Their expertise and support are outstanding. The radar integration is particularly impressive.', '2024-10-28', 1, 1),
(2, 7, 'review-navtech-2', 'Jennifer Thompson', 'Yacht Owner', 'Northern Star', 'GPS & Radar Upgrade', 4.5, 5, 4, 5, 5, 4, 'Professional service from start to finish. The navigation equipment is top-tier and the training provided was comprehensive. Highly recommend for serious yachting needs.', '2024-09-14', 1, 0),
(3, 7, 'review-navtech-3', 'Mark Stevens', 'Technical Manager', 'Aphrodite', 'System Integration', 5, 5, 5, 4, 5, 4, 'NavTech integrated our navigation, communication, and monitoring systems seamlessly. Their technical knowledge is second to none.', '2024-07-30', 1, 0);

-- Marine AV Technologies (Tier 1) - id: 9
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 9, 'review-marineav-1', 'Alexandra Reed', 'Yacht Owner', 'Meridian', 'Premium AV System', 5, 5, 5, 5, 5, 4, 'Marine AV created a stunning audio-visual experience throughout our yacht. From the cinema room to outdoor speakers, everything is perfectly integrated. Exceptional quality.', '2024-11-05', 1, 1),
(2, 9, 'review-marineav-2', 'Thomas Wilson', 'Project Manager', 'Silver Wave', 'Home Theater Installation', 4.5, 5, 4, 4, 5, 4, 'Outstanding home theater system with cinema-quality sound and video. The installation team was professional and the result exceeded expectations.', '2024-08-25', 1, 0),
(3, 9, 'review-marineav-3', 'Lisa Chang', 'Interior Designer', 'Azure Dream', 'Multi-Zone Audio', 4.5, 5, 5, 4, 5, 4, 'The multi-zone audio system Marine AV installed is incredible. Perfect sound in every space, easy to control, and beautifully integrated.', '2024-06-12', 1, 0);

-- Superyacht Integration Solutions (Tier 2) - id: 12
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 12, 'review-superint-1', 'Captain William Foster', 'Master Captain', 'Lady Michelle', 'Complete IT/AV Integration', 5, 5, 5, 5, 5, 5, 'Superyacht Integration Solutions delivered a world-class integration on our 180-foot vessel. Every system communicates perfectly and the level of automation is impressive. Worth every penny.', '2024-10-20', 1, 1),
(2, 12, 'review-superint-2', 'Richard Blackwell', 'Owner Representative', 'Odyssey', 'Full Systems Refit', 5, 5, 5, 4, 5, 4, 'A major refit project handled with absolute professionalism. The team coordinated with multiple vendors and delivered on time. The integrated system is exceptional.', '2024-08-08', 1, 1),
(3, 12, 'review-superint-3', 'Emma Richardson', 'Yacht Manager', 'Quantum', 'Network & Security Upgrade', 4.5, 5, 5, 4, 5, 4, 'The network infrastructure they installed is enterprise-grade yet easy to manage. Security features are comprehensive and the documentation is excellent.', '2024-05-15', 1, 0);

-- Maritime Technology Partners (Tier 2) - id: 13
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 13, 'review-maritime-1', 'Captain James Peterson', 'Professional Captain', 'Hemisphere', 'Navigation & Communication Suite', 5, 5, 5, 5, 5, 4, 'Maritime Technology Partners provided a comprehensive navigation and communication system that has performed flawlessly across the Atlantic. Their support is outstanding.', '2024-11-08', 1, 1),
(2, 13, 'review-maritime-2', 'Sophie Laurent', 'Owner', 'Belle Étoile', 'Complete Integration', 4.5, 5, 5, 4, 5, 4, 'Professional team that delivered a sophisticated integration on our 160-foot yacht. The lighting control system alone is worth highlighting - absolutely brilliant.', '2024-09-03', 1, 0),
(3, 13, 'review-maritime-3', 'Michael O Brien', 'Technical Director', 'Irish Rover', 'Monitoring System', 5, 5, 4, 5, 5, 4, 'The advanced monitoring system gives us complete visibility into all yacht systems. Early warning of potential issues has already prevented problems.', '2024-07-21', 1, 0);

-- Superyacht Systems Global (Tier 3) - id: 16
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 16, 'review-ssg-1', 'Captain Alessandro Russo', 'Master Captain', 'Gioia', 'Complete Technology Integration', 5, 5, 5, 5, 5, 5, 'Superyacht Systems Global is the gold standard for superyacht technology. Their 25 years of experience shows in every detail. Our 250-foot vessel has the most advanced systems available.', '2024-10-30', 1, 1),
(2, 16, 'review-ssg-2', 'Lady Victoria Worthington', 'Yacht Owner', 'Enigma', 'Full Vessel Technology Suite', 5, 5, 5, 5, 5, 4, 'Simply the best in the business. From initial consultation to final commissioning, every interaction was world-class. The systems are intuitive yet incredibly sophisticated.', '2024-08-15', 1, 1),
(3, 16, 'review-ssg-3', 'Pierre Dubois', 'Project Manager', 'L Atlantique', 'New Build Integration', 5, 5, 5, 5, 5, 5, 'Worked with SSG on a 300-foot new build. Their coordination with the shipyard and other contractors was impeccable. The technology package they delivered is state-of-the-art.', '2024-06-28', 1, 1),
(4, 16, 'review-ssg-4', 'Jonathan Harris', 'Owner Representative', 'Phoenix Rising', 'Major Refit', 5, 5, 5, 4, 5, 4, 'A complex refit project managed brilliantly by SSG. They upgraded every system while maintaining full functionality throughout. The final result is extraordinary.', '2024-04-10', 1, 0);

-- Marine Tech Innovations (Tier 3) - id: 17
INSERT INTO vendors_vendor_reviews (_order, _parent_id, id, reviewer_name, reviewer_role, yacht_name, project_type, overall_rating, ratings_quality, ratings_communication, ratings_timeliness, ratings_professionalism, ratings_value_for_money, review_text, review_date, verified, featured) VALUES
(1, 17, 'review-mti-1', 'Captain Hans Weber', 'Professional Captain', 'Aurora Borealis', 'Complete Systems Package', 5, 5, 5, 5, 5, 5, 'Marine Tech Innovations delivered an award-winning technology integration on our 220-foot explorer yacht. The climate control and automation systems are particularly impressive. Absolute perfection.', '2024-11-02', 1, 1),
(2, 17, 'review-mti-2', 'Anastasia Volkov', 'Yacht Owner', 'White Pearl', 'Luxury Integration', 5, 5, 5, 5, 5, 4, 'MTI created a seamless technology experience throughout our yacht. Every system works in perfect harmony. Their attention to detail and innovative solutions set them apart.', '2024-09-18', 1, 1),
(3, 17, 'review-mti-3', 'Charles Montgomery', 'Technical Consultant', 'Liberty', 'Advanced Automation', 5, 5, 5, 5, 5, 5, 'The automation system MTI designed is years ahead of competitors. Intelligent, intuitive, and incredibly sophisticated. Their 22 years of experience is evident in every aspect.', '2024-07-05', 1, 1),
(4, 17, 'review-mti-4', 'Isabella Romano', 'Owner Representative', 'Dolce Vita', 'Entertainment Systems', 5, 5, 5, 4, 5, 4, 'World-class entertainment and media systems installed throughout our 190-foot yacht. The quality is exceptional and the user experience is flawless.', '2024-05-22', 1, 0);
