// Import map for Payload CMS admin panel
// This file is auto-generated by Payload CMS
// You can customize imports here if needed

import { GeocodingButton } from '@/payload/fields/GeocodingButton';

export const importMap = {
  '@/payload/fields/GeocodingButton#GeocodingButton': GeocodingButton,
};
